remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
title: Meredith Sliger: Portfolio
description: A showcase of my projects in R, Python, SQL, Tableau, and more.
show_downloads: false

markdown: kramdown
