remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-remote-theme

title: Meredith Sliger
description: >
  Data Science | Python • R • SQL • Tableau

show_downloads: false
markdown: kramdown
